version: 0.0
os: linux

files:
  - source: /
    destination: /var/www/html/knolzi-vanshika
    overwrite: true

permissions:
  - object: /var/www/html/knolzi-vanshika
    owner: ubuntu
    group: www-data
    mode: 775
    type:
      - directory
      - file

hooks:
  AfterInstall:
    - location: scripts/deploy.sh
      timeout: 300
      runas: ubuntu
