<?php

return [
    'currency_list' => [
       
        ['code' => 'INR','name' => 'India','icon'=>'₹'],
        ['code' => 'EUR','name' => 'Austria','icon'=>'€'],
        ['code' => 'EUR','name' => 'Italy','icon'=>'€'],
        ['code' => 'EUR','name' => 'Germany','icon'=>'€'],
        ['code' => 'AUD','name' => 'Australia','icon'=>'$'],
        ['code' => 'CAD','name' => 'Canada','icon'=>'$'],
        ['code' => 'USD','name' => 'United States','icon'=>'$'],
        ['code' => 'AFN','name' => 'Afghanistan','icon'=>'؋ '],
        ['code' => 'ARS','name' => 'Argentina','icon'=>'$'],
        ['code' => 'AWG','name' => 'Argentina','icon'=>'ƒ'],
        ['code' => 'AZN','name' => 'Azerbaijan','icon'=>'₼'],
        ['code' => 'BSD','name' => 'Bahamas','icon'=>'$'],
        ['code' => 'BBD','name' => 'Barbados','icon'=>'$'],
        ['code' => 'BDT','name' => 'Bangladesh','icon'=>'৳'],
        ['code' => 'BYN','name' => 'Belarus','icon'=>'Br'],
        ['code' => 'BZD','name' => 'Belize','icon'=>'$'],
        ['code' => 'BMD','name' => 'Bermuda','icon'=>'$'],
        ['code' => 'BOP','name' => 'Bolivia','icon'=>'Bs'],
        ['code' => 'BAM','name' => 'Bosnia And Herzegovina','icon'=>'KM'],
        ['code' => 'BWP','name' => 'Botswana','icon'=>'P'],
        ['code' => 'BGN','name' => 'Bulgaria','icon'=>'лв'],
        ['code' => 'BRL','name' => 'Brazil','icon'=>'$'],
        ['code' => 'BND','name' => 'Brunei Darussalam','icon'=>'$'],
        ['code' => 'KHR','name' => 'Cambodia','icon'=>'៛'],
        ['code' => 'KYD','name' => 'Cayman Islands','icon'=>'$'],
        ['code' => 'CLP','name' => 'Chile','icon'=>'$'],
        ['code' => 'CNY','name' => 'China','icon'=>'¥'],
        ['code' => 'COP','name' => 'Colombia','icon'=>'$'],
        ['code' => 'CRC','name' => 'Costa Rica','icon'=>'₡'],
        ['code' => 'HRK','name' => 'Croatia','icon'=>'kn'],
        ['code' => 'CUP','name' => 'Cuba','icon'=>'₱'],
        ['code' => 'CZK','name' => 'Czech Republic','icon'=>'Kč'],
        ['code' => 'DKK','name' => 'Denmark','icon'=>'kr'],
        ['code' => 'DOP','name' => 'Dominican Republic','icon'=>'$'],
        ['code' => 'XCD','name' => 'Grenada','icon'=>'$'],
        ['code' => 'EGP','name' => 'Egypt','icon'=>'£'],
        ['code' => 'SVC','name' => 'El Salvador','icon'=>'$'],
        ['code' => 'EEK','name' => 'Estonia','icon'=>'Kr'],
        ['code' => 'FKP','name' => 'Falkland Islands','icon'=>'£'],
        ['code' => 'FJD','name' => 'Fiji','icon'=>'$'],
        ['code' => 'GHC','name' => 'Ghana','icon'=>'¢'],
        ['code' => 'GIP','name' => 'Gibraltar','icon'=>'£'],
        ['code' => 'GTQ','name' => 'Guatemala','icon'=>'Q'],
        ['code' => 'GGP','name' => 'Guernsey','icon'=>'Q'],
        ['code' => 'GYD','name' => 'Guyana','icon'=>'$'],
        ['code' => 'HNL','name' => 'Honduras','icon'=>'L'],
        ['code' => 'HKD','name' => 'Hong Kong','icon'=>'$'],
        ['code' => 'HUF','name' => 'Hungary','icon'=>'Ft'],
        ['code' => 'ISK','name' => 'Iceland','icon'=>'íkr'],
        ['code' => 'IDR','name' => 'Indonesia','icon'=>'Rp'],
        ['code' => 'IRR','name' => 'Iran','icon'=>'$'],
        ['code' => 'IMP','name' => 'Isle of Man Pound','icon'=>'£'],
        ['code' => 'ILS','name' => 'Israel','icon'=>'₪'],
        ['code' => 'JMD','name' => 'Jamaica','icon'=>'$'],
        ['code' => 'JPY','name' => 'Japan','icon'=>'¥'],
        ['code' => 'JEP','name' => 'Jersey','icon'=>'£'],
        ['code' => 'KZT','name' => 'Kazakhstan','icon'=>'₸'],
        ['code' => 'KPW','name' => 'Korea (North)','icon'=>'₩'],
        ['code' => 'KRW','name' => 'Korea (South)','icon'=>'₩'],
        ['code' => 'KGS','name' => 'Kyrgyzstan','icon'=>'лв'],
        ['code' => 'LAK','name' => 'Laos','icon'=>'₭'],
        ['code' => 'LVL','name' => 'Latvia','icon'=>'€'],
        ['code' => 'LBP','name' => 'Lebanon','icon'=>'€'],
        ['code' => 'LRD','name' => 'Liberia','icon'=>'$'],
        ['code' => 'LTL','name' => 'Lithuania','icon'=>'€'],
        ['code' => 'MKD','name' => 'Macedonia','icon'=>'ден'],
        ['code' => 'MYR','name' => 'Malaysia','icon'=>'RM'],
        ['code' => 'MUR','name' => 'Mauritius','icon'=>'Rs'],
        ['code' => 'MXN','name' => 'Mexico','icon'=>'$'],
        ['code' => 'MNT','name' => 'Mongolia','icon'=>'₮'],
        ['code' => 'MZN','name' => 'Mozambique','icon'=>'MT'],
        ['code' => 'NAD','name' => 'Namibia','icon'=>'$'],
        ['code' => 'NPR','name' => 'Nepal','icon'=>'Rs.'],
        ['code' => 'ANG','name' => 'Netherland','icon'=>'ƒ'],
        ['code' => 'NZD','name' => 'New Zealand','icon'=>'$'],
        ['code' => 'NIO','name' => 'Nicaragua','icon'=>'$'],
        ['code' => 'NGN','name' => 'Nigeria','icon'=>'₦'],
        ['code' => 'NOK','name' => 'Norway','icon'=>'kr'],
        ['code' => 'OMR','name' => 'Oman','icon'=>'$'],
        ['code' => 'PKR','name' => 'Pakistan','icon'=>'Rs'],
        ['code' => 'PAB','name' => 'Panama','icon'=>'B/.'],
        ['code' => 'PYG','name' => 'Paraguay','icon'=>'₲'],
        ['code' => 'PEN','name' => 'Peru','icon'=>'S/.'],
        ['code' => 'PHP','name' => 'Philippines','icon'=>'₱'],
        ['code' => 'PLN','name' => 'Poland','icon'=>'zł'],
        ['code' => 'QAR','name' => 'Qatar','icon'=>'$'],
        ['code' => 'RON','name' => 'Romania','icon'=>'L'],
        ['code' => 'RUB','name' => 'Russia','icon'=>'₽'],
        ['code' => 'SHP','name' => 'Saint Helena','icon'=>'£'],
        ['code' => 'SAR','name' => 'Saudi Arabia','icon'=>'$'],
        ['code' => 'RSD','name' => 'Serbia','icon'=>'din'],
        ['code' => 'SCR','name' => 'Seychelles','icon'=>'Rs'],
        ['code' => 'SGD','name' => 'Singapore','icon'=>'$'],
        ['code' => 'SBD','name' => 'Solomon Islands','icon'=>'$'],
        ['code' => 'SOS','name' => 'Somalia','icon'=>'$'],
        ['code' => 'ZAR','name' => 'South Africa','icon'=>'R'],
        ['code' => 'LKR','name' => 'Sri Lanka','icon'=>'Rs'],
        ['code' => 'SEK','name' => 'Sweden','icon'=>'kr'],
        ['code' => 'CHF','name' => 'Switzerland','icon'=>'CHf'],
        ['code' => 'SRD','name' => 'Suriname','icon'=>'$'],
        ['code' => 'SYP','name' => 'Syria','icon'=>'£S'],
        ['code' => 'TWD','name' => 'Taiwan','icon'=>'$'],
        ['code' => 'TTD','name' => 'Trinidad and Tobago','icon'=>'$'],
        ['code' => 'TRY','name' => 'Turkey','icon'=>'₺'],
        ['code' => 'TRL','name' => 'Turkey','icon'=>'₺'],
        ['code' => 'TVD','name' => 'Tuvalu','icon'=>'$'],
        ['code' => 'UAH','name' => 'Ukraine','icon'=>'₴'],
        ['code' => 'GBP','name' => 'United Kingdom','icon'=>'£'],
        ['code' => 'UGX','name' => 'Ugandan','icon'=>'USh'],
        ['code' => 'UYU','name' => 'Uruguay','icon'=>'$'],
        ['code' => 'UZS','name' => 'Uzbekistan','icon'=>'лв'],
        ['code' => 'VEF','name' => 'Venezuela','icon'=>'Bs'],
        ['code' => 'VND','name' => 'Viet Nam','icon'=>'₫'],
        ['code' => 'YER','name' => 'Yemen','icon'=>'$'],
        ['code' => 'ZWD','name' => 'Zimbabwe','icon'=>'$'],

    ],
];
